"use client";

import Link from "next/link";
import {
  ArrowRight, Building2, ChevronRight, CircleDollarSign, Crosshair, Database,
  ExternalLink, FileText, Gauge, Layers3, LoaderCircle, Mail, Menu, Newspaper,
  Phone, Radar, RefreshCw, Search, SlidersHorizontal, Target, Users, X
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type View="overview"|"opportunities"|"profile"|"dossier"|"market"|"pricing";
type Analysis={company:string;hostname:string;source:"website"|"curated-fallback";categories:{name:string;applications:string;confidence:number}[];idealProjects:string[];analyzedAt:string};
type Signal={id:string;title:string;published:string|null;buyer:string;noticeType:string;source:string;country:string;stage:string;relevance:number;customerScore:number;matchedProducts:string[];why:string;href:string;live:boolean};
type Project={id:string;canonicalKey:string;name:string;country:string;currentStage:string;primaryAccount:string;opportunityScore:number;dataConfidence:number;matchedProducts:string[];signalCount:number;sourceCount:number;sources:string[];firstSeen:string|null;lastSeen:string|null;why:string;timeline:Signal[]};
type SourceStatus={source:string;ok:boolean;count:number;error:string|null};
type Persistence={enabled:boolean;savedProjects:number;savedSignals:number;error:string|null};
type Enrichment={ok:boolean;company:string;website:string|null;websiteTitle:string|null;phones:string[];emails:string[];linkedinCompany:string|null;people:{name:string;title:string;linkedin:string;snippet:string}[];mentions:{title:string;url:string;snippet:string;source:string;published?:string}[];confidence:{website:number;contacts:number;people:number;mentions:number}};

const nav=[["overview","Overview",Radar],["opportunities","Projects",Crosshair],["profile","Market profile",SlidersHorizontal],["market","Market intelligence",Gauge],["pricing","ROI & pricing",CircleDollarSign]] as const;
const defaultAnalysis:Analysis={company:"Systemair",hostname:"systemair.com",source:"curated-fallback",categories:[{name:"Air handling units",applications:"Hospitals · hotels · offices · schools",confidence:98},{name:"Commercial ventilation",applications:"Broad commercial buildings",confidence:98},{name:"Fire & smoke ventilation",applications:"Hospitals · public buildings · logistics",confidence:94},{name:"Heat recovery",applications:"Energy-efficient new build · renovation",confidence:92}],idealProjects:["Hospitals","Hotels","Offices","Schools","Public buildings","Logistics","Renovation"],analyzedAt:""};

function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="metric"><span className="micro">{label}</span><strong>{value}</strong><small>{note}</small></article>}
function targetFor(stage:string){if(stage==="planning")return{role:"Architect / MEP consultant",reason:"Early planning stage — influence design intent before specification hardens."};if(stage==="permit")return{role:"Owner / developer + engineering team",reason:"Permit stage — project is validated while technical choices may still move."};return{role:"Procurement / contractor / integrator",reason:"Procurement stage — specification influence is lower, so pursue buying and delivery stakeholders."}}
function timing(stage:string){if(stage==="planning")return"Engage now — specification window";if(stage==="permit")return"Engage within days";return"Act now — procurement active"}
function dateText(v?:string|null){if(!v)return"Date unavailable";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString()}

export default function ProjectSignalApp(){
 const[view,setView]=useState<View>("overview");const[open,setOpen]=useState(false);const[website,setWebsite]=useState("https://www.systemair.com");const[analysis,setAnalysis]=useState<Analysis>(defaultAnalysis);const[profileLoading,setProfileLoading]=useState(false);const[profileError,setProfileError]=useState("");
 const[projects,setProjects]=useState<Project[]>([]);const[sources,setSources]=useState<SourceStatus[]>([]);const[rawSignalCount,setRawSignalCount]=useState(0);const[multiSignalCount,setMultiSignalCount]=useState(0);const[persistence,setPersistence]=useState<Persistence>({enabled:false,savedProjects:0,savedSignals:0,error:null});const[feedLoading,setFeedLoading]=useState(true);const[feedError,setFeedError]=useState("");const[fetchedAt,setFetchedAt]=useState("");const[selected,setSelected]=useState<Project|null>(null);const[actionOutput,setActionOutput]=useState("");
 const[enrichment,setEnrichment]=useState<Enrichment|null>(null);const[enriching,setEnriching]=useState(false);const[enrichError,setEnrichError]=useState("");const[query,setQuery]=useState("");
 const company=analysis.company||analysis.hostname;const go=(v:View)=>{setView(v);setOpen(false);window.scrollTo({top:0,behavior:"instant"})};

 useEffect(()=>{try{const saved=localStorage.getItem("projectsignal-profile");if(saved){const p=JSON.parse(saved);setAnalysis(p);setWebsite(`https://${p.hostname}`)}}catch{}},[]);
 useEffect(()=>{loadProjects(analysis)},[analysis]);

 async function loadProjects(p:Analysis){setFeedLoading(true);setFeedError("");try{const qs=new URLSearchParams({company:p.company,products:p.categories.map(x=>x.name).join("|"),countries:"NL|BE"});const r=await fetch(`/api/projects?${qs.toString()}`,{cache:"no-store"});const d=await r.json();if(!d.ok)throw new Error(d.error||"Project entity layer unavailable");setProjects(d.projects||[]);setSources(d.sources||[]);setRawSignalCount(d.rawSignalCount||0);setMultiSignalCount(d.multiSignalProjectCount||0);setPersistence(d.persistence||{enabled:false,savedProjects:0,savedSignals:0,error:null});setFetchedAt(d.generatedAt||"")}catch(e){setFeedError(e instanceof Error?e.message:"Projects unavailable");setProjects([])}finally{setFeedLoading(false)}}
 async function analyze(){setProfileLoading(true);setProfileError("");try{const r=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({website})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Analysis failed");setAnalysis(d);localStorage.setItem("projectsignal-profile",JSON.stringify(d));go("opportunities")}catch(e){setProfileError(e instanceof Error?e.message:"Analysis failed")}finally{setProfileLoading(false)}}
 async function enrich(project:Project){setEnriching(true);setEnrichError("");setEnrichment(null);try{const qs=new URLSearchParams({company:project.primaryAccount,country:project.country});const r=await fetch(`/api/enrich-account?${qs.toString()}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Enrichment failed");setEnrichment(d)}catch(e){setEnrichError(e instanceof Error?e.message:"Enrichment failed")}finally{setEnriching(false)}}
 function openDossier(project:Project){setSelected(project);setActionOutput("");setEnrichment(null);setEnrichError("");go("dossier");enrich(project)}

 const high=useMemo(()=>projects.filter(x=>x.opportunityScore>=80).length,[projects]);const early=useMemo(()=>projects.filter(x=>x.currentStage==="planning"||x.currentStage==="permit").length,[projects]);const top=projects[0]||null;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return projects;return projects.filter(x=>`${x.name} ${x.primaryAccount} ${x.country} ${x.currentStage} ${x.sources.join(" ")} ${x.matchedProducts.join(" ")}`.toLowerCase().includes(q))},[projects,query]);
 function contactReadiness(project:Project){let s=32;if(project.primaryAccount&&!/public buyer|public authority|not yet identified/i.test(project.primaryAccount))s+=18;if(project.signalCount>1)s+=10;if(project.sourceCount>1)s+=8;if(project.matchedProducts.length)s+=12;if(project.currentStage==="planning"||project.currentStage==="permit")s+=6;if(enrichment?.emails?.length||enrichment?.phones?.length)s+=10;if(enrichment?.people?.length)s+=8;return Math.min(98,s)}
 function generateAction(kind:"email"|"call"|"proposal"){if(!selected)return;const products=selected.matchedProducts.length?selected.matchedProducts.join(", "):analysis.categories.slice(0,2).map(x=>x.name).join(", ");const target=targetFor(selected.currentStage);const person=enrichment?.people?.[0];const salutation=person?.name||"[Name]";if(kind==="email")setActionOutput(`Subject: ${selected.name} — ${products}\n\nHi ${salutation},\n\nWe are tracking ${selected.name}. ${selected.signalCount>1?`We have seen ${selected.signalCount} public project signals across ${selected.sourceCount} sources.`:`We identified a public project signal.`}\n\n${selected.primaryAccount} appears connected to the current ${selected.currentStage} stage, and ${products} match our active portfolio at ${company}.\n\nGiven the timing, would a short 15-minute call be useful to understand the technical requirements and next decision point?\n\nBest regards,\n[Sales rep]\n${company}`);if(kind==="call")setActionOutput(`CALL BRIEF\n\nProject: ${selected.name}\nCurrent stage: ${selected.currentStage}\nSignals combined: ${selected.signalCount}\nSources: ${selected.sources.join(", ")}\nTarget account: ${selected.primaryAccount}\nTarget role: ${target.role}\nSuggested contact: ${person?.name||"identify named decision maker"}\nWhy now: ${target.reason}\nRelevant products: ${products}\n\nOPENING\n“We are following ${selected.name} and noticed the project is at ${selected.currentStage} stage. I wanted to understand who is leading the building-services specification.”\n\nQUESTIONS\n1. Who owns the HVAC/building-services specification?\n2. Which product families are already specified?\n3. When is the next design/procurement milestone?\n4. Are alternative suppliers still being evaluated?\n5. Who should receive technical documentation?`);if(kind==="proposal")setActionOutput(`PROJECT OPPORTUNITY BRIEF\n\nProject: ${selected.name}\nCustomer portfolio: ${company}\nTarget account: ${selected.primaryAccount}\nCurrent stage: ${selected.currentStage}\nOpportunity score: ${selected.opportunityScore}/100\nData confidence: ${selected.dataConfidence}%\nPublic signals: ${selected.signalCount} across ${selected.sourceCount} source(s)\nRelevant portfolio: ${products}\n\nCOMMERCIAL INTERPRETATION\n${selected.why}\n\nNEXT STEP\nConfirm stakeholder map → validate specification owner → send technical pack → schedule project review.`)}
 const target=selected?targetFor(selected.currentStage):null;

 return <div className="shell"><aside className={`sidebar ${open?"open":""}`}><div className="brandRow"><button className="brand" onClick={()=>go("overview")}><span className="brandMark"><Radar size={20}/></span>PROJECTSIGNAL</button><button className="icon mobile" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="workspace"><span className="micro inverse">WORKSPACE</span><b>Benelux / Building systems</b><span>{company} live profile</span></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><Icon size={17}/>{label}</button>)}</nav><div className="sideFoot"><span className="dot"/><div><b>Project Entity MVP</b><span>Signals → canonical projects → dossier → sales action</span></div></div></aside>
 <main><header className="topbar"><button className="icon mobile" onClick={()=>setOpen(true)}><Menu size={19}/></button><span className="micro">PROJECTSIGNAL / {view.toUpperCase()}</span><div className="topActions"><Link className="textBtn" href="/live">Raw signals <ExternalLink size={14}/></Link><button className="textBtn" onClick={()=>go("profile")}>Edit profile <ArrowRight size={15}/></button></div></header>

 {view==="overview"&&<section className="page"><div className="hero"><div><span className="kicker"><span className="dot orange"/> PROJECT-CENTRIC SALES INTELLIGENCE</span><h1>From fragmented signals to <em>one actionable project.</em></h1><p>ProjectSignal now resolves public planning, permit and procurement records into canonical projects, builds a timeline, ranks each project for your portfolio and prepares the route to a sales conversation.</p><div className="actions"><button className="primary" onClick={()=>go("opportunities")}>Open qualified projects <ArrowRight size={16}/></button><button className="secondary" onClick={()=>go("profile")}>Analyse another company</button></div></div><div className="railCard"><div className="railHead"><span className="micro inverse">TOP PROJECT FOR {company.toUpperCase()}</span><span>{top?`${top.opportunityScore} / 100`:"—"}</span></div><div className="railProject"><b>{top?.name||"Building canonical projects…"}</b><small>{top?`${top.signalCount} signal(s) · ${top.sourceCount} source(s) · ${top.country}`:"NL + BE public sources"}</small></div><div className="rail">{["Planning","Permit","Specification","Procurement","Delivery"].map((s,i)=>{const idx=top?.currentStage==="planning"?0:top?.currentStage==="permit"?1:3;return <div className={`${idx===i?"current":""} ${idx>i?"done":""}`} key={s}><span/><b>{s}</b>{idx===i&&<small>Current project stage</small>}</div>})}</div>{top&&<button className="railAction railActionButton" onClick={()=>openDossier(top)}><span className="micro inverse">NEXT COMMERCIAL MOVE</span><b>{timing(top.currentStage)}</b><small>Open Project Dossier 2.0 →</small></button>}</div></div><div className="thesis"><article><span className="micro">RESOLVE</span><b>Many signals, one project.</b><p>Similar public records are clustered into a canonical entity.</p></article><article className="accent"><span className="micro">UNDERSTAND</span><b>Timeline + provenance.</b><p>See when the project moved and which sources corroborate it.</p></article><article><span className="micro">ACT</span><b>Account + people + outreach.</b><p>Move from project intelligence to a sales conversation.</p></article></div></section>}

 {view==="profile"&&<section className="page"><div className="intro"><div><span className="micro">MARKET PROFILE</span><h1>Teach ProjectSignal what your company can sell.</h1><p>The active product profile is used when canonical projects are scored and prioritised.</p></div></div><div className="profileGrid"><div className="form"><label>COMPANY WEBSITE<input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://www.company.com"/></label><div><span className="micro">QUICK DEMOS</span><div className="actions"><button className="secondary" onClick={()=>setWebsite("https://www.systemair.com")}>Systemair</button><button className="secondary" onClick={()=>setWebsite("https://www.renson.net")}>Renson</button><button className="secondary" onClick={()=>setWebsite("https://www.zehnder.nl")}>Zehnder</button><button className="secondary" onClick={()=>setWebsite("https://www.daikin.be")}>Daikin</button></div></div>{profileError&&<p className="urgent">{profileError}</p>}<button className="primary" onClick={analyze} disabled={profileLoading}>{profileLoading?<><LoaderCircle size={16} className="spin"/> Analysing…</>:<>Analyse portfolio & rebuild projects <ArrowRight size={16}/></>}</button></div><aside className="derived"><span className="micro">ACTIVE PROFILE · {analysis.source==="website"?"WEBSITE-DETECTED":"CURATED FALLBACK"}</span><h2>{company}</h2>{analysis.categories.map(x=><div key={x.name}><b>{x.name}</b><span>{x.applications} · confidence {x.confidence}%</span></div>)}</aside></div></section>}

 {view==="opportunities"&&<section className="page"><div className="intro"><div><span className="micro">CANONICAL PROJECTS FOR {company.toUpperCase()}</span><h1>Qualified projects, not duplicate source records.</h1><p>{rawSignalCount||"Live"} raw signals are resolved into {projects.length||"…"} project entities. Open any project to see the combined timeline and source provenance.</p></div><button className="secondary" onClick={()=>loadProjects(analysis)} disabled={feedLoading}><RefreshCw size={15}/>{feedLoading?"Rebuilding…":"Refresh projects"}</button></div><div className="metrics"><Metric label="QUALIFIED PROJECTS" value={feedLoading?"—":String(projects.length)} note={`from ${rawSignalCount} raw signals`}/><Metric label="MULTI-SIGNAL PROJECTS" value={feedLoading?"—":String(multiSignalCount)} note="corroborated by >1 record"/><Metric label="HIGH FIT" value={feedLoading?"—":String(high)} note="opportunity score ≥ 80"/><Metric label="EARLY STAGE" value={feedLoading?"—":String(early)} note="planning + permit"/></div>{feedError&&<div className="liveError"><b>Project entity layer unavailable</b><span>{feedError}</span></div>}<div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project, account, product, source…"/></div><span className="micro">{persistence.enabled?(persistence.error?"DB ERROR":"PERSISTED TO DATABASE"):"EPHEMERAL MODE · DB NOT CONFIGURED"}</span></div><div className="tableWrap"><table><thead><tr><th>Fit</th><th>Canonical project</th><th>Signals</th><th>Products</th><th>Stage</th><th>Known account</th><th>Confidence</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="clickable" onClick={()=>openDossier(p)}><td><span className="score">{p.opportunityScore}</span></td><td><b>{p.name}</b><span>{p.country} · last signal {dateText(p.lastSeen)}</span></td><td><b>{p.signalCount}</b><span>{p.sourceCount} source(s)</span></td><td>{p.matchedProducts.length?p.matchedProducts.slice(0,2).join(" · "):"Portfolio fit not explicit"}</td><td><span className={`stage stage-${p.currentStage}`}>{p.currentStage}</span></td><td>{p.primaryAccount}</td><td><b>{p.dataConfidence}%</b><span>data confidence</span></td></tr>)}</tbody></table>{!feedLoading&&!filtered.length&&<div className="emptyState">No projects match the current filter.</div>}</div></section>}

 {view==="dossier"&&selected&&<section className="page dossierPage"><button className="back" onClick={()=>go("opportunities")}>← Back to canonical projects</button><div className="projectHead"><div><span className="micro">PROJECT DOSSIER 2.0 / {selected.id.toUpperCase()}</span><h1>{selected.name}</h1><p>{selected.country} · {selected.signalCount} public signal(s) · {selected.sourceCount} independent source(s)</p></div><div className="bigScore"><span>OPPORTUNITY SCORE</span><strong>{selected.opportunityScore}</strong><small>/100</small></div></div><div className="dossierSummary"><Metric label="CURRENT STAGE" value={selected.currentStage.toUpperCase()} note={timing(selected.currentStage)}/><Metric label="DATA CONFIDENCE" value={`${selected.dataConfidence}%`} note="entity + source completeness"/><Metric label="PUBLIC SIGNALS" value={String(selected.signalCount)} note={`${selected.sourceCount} source(s) combined`}/><Metric label="CONTACT READINESS" value={`${contactReadiness(selected)}%`} note="account + public enrichment"/></div>
 <div className="dossierGrid"><div className="dossierMain">
 <section className="panel"><div className="panelHead"><div><span className="micro">CANONICAL PROJECT</span><h2>Why these records belong together</h2></div><Layers3 size={20}/></div><p>{selected.why}</p>{selected.matchedProducts.map(p=><div className="reason" key={p}><span>✓</span>{p} matched to the active {company} portfolio</div>)}<div className="reason"><span>✓</span>Canonical key keeps the project separate from unrelated permits and tenders.</div></section>
 <section className="panel"><div className="panelHead"><div><span className="micro">PROJECT TIMELINE</span><h2>{selected.signalCount} signal(s) combined into one history</h2></div><Database size={20}/></div><div className="projectTimeline">{selected.timeline.map((s,i)=><article className="timelineSignal" key={s.id}><div className="timelineIndex">{i+1}</div><div><div className="timelineMeta"><span className={`stage stage-${s.stage}`}>{s.stage}</span><span>{dateText(s.published)}</span><span>{s.source}</span></div><b>{s.title}</b><p>{s.buyer} · {s.noticeType}</p><a href={s.href} target="_blank" rel="noreferrer">Open original record <ExternalLink size={12}/></a></div></article>)}</div></section>
 <section className="panel"><div className="panelHead"><div><span className="micro">STAKEHOLDER ROUTE</span><h2>Who should sales target at this stage?</h2></div></div><div className="stakeFlow"><article className="stakeKnown"><span>KNOWN ACCOUNT</span><b>{selected.primaryAccount}</b><small>Best account identified across combined signals</small></article><ArrowRight size={18}/><article><span>PRIORITY ROLE</span><b>{target?.role}</b><small>{target?.reason}</small></article><ArrowRight size={18}/><article className={enrichment?.people?.length?"stakeKnown":"stakePending"}><span>NAMED CONTACT</span><b>{enrichment?.people?.[0]?.name||"Research in progress"}</b><small>{enrichment?.people?.[0]?.title||"Public web / LinkedIn enrichment"}</small></article></div></section>
 <section className="panel"><div className="panelHead"><div><span className="micro">ACCOUNT DOSSIER</span><h2>{selected.primaryAccount}</h2></div><Building2 size={20}/></div>{enriching?<div className="liveLoading"><LoaderCircle size={18} className="spin"/> Researching public web sources…</div>:enrichError?<div className="liveError"><b>Enrichment unavailable</b><span>{enrichError}</span></div>:enrichment&&<><div className="accountFacts"><div><span>Website</span><b>{enrichment.website?<a href={enrichment.website} target="_blank" rel="noreferrer">{enrichment.website.replace(/^https?:\/\//,'')} <ExternalLink size={12}/></a>:"Not found"}</b></div><div><span>Phone</span><b>{enrichment.phones[0]||"Not found"}</b></div><div><span>Email</span><b>{enrichment.emails[0]||"Not found"}</b></div><div><span>LinkedIn</span><b>{enrichment.linkedinCompany?<a href={enrichment.linkedinCompany} target="_blank" rel="noreferrer">Company profile <ExternalLink size={12}/></a>:"Not found"}</b></div></div><div className="confidenceLine"><span>Website {enrichment.confidence.website}%</span><span>Contacts {enrichment.confidence.contacts}%</span><span>People {enrichment.confidence.people}%</span><span>Mentions {enrichment.confidence.mentions}%</span></div></>}</section>
 <section className="panel"><div className="panelHead"><div><span className="micro">RELEVANT PEOPLE</span><h2>Public professional profiles</h2></div><Users size={20}/></div>{enriching?<p>Searching roles…</p>:enrichment?.people?.length?<div className="peopleList">{enrichment.people.map(p=><article key={p.linkedin}><div><b>{p.name}</b><span>{p.title}</span><small>{p.snippet}</small></div><a href={p.linkedin} target="_blank" rel="noreferrer">LinkedIn <ExternalLink size={12}/></a></article>)}</div>:<p>No named public profiles found automatically. ProjectSignal does not invent people when public evidence is missing.</p>}</section>
 <section className="panel"><div className="panelHead"><div><span className="micro">RECENT INTELLIGENCE</span><h2>Latest public mentions for the target account</h2></div><Newspaper size={20}/></div>{enriching?<p>Collecting mentions…</p>:enrichment?.mentions?.length?<div className="mentionList">{enrichment.mentions.slice(0,8).map((m,i)=><article key={`${m.url}-${i}`}><span>{m.published?dateText(m.published):m.source}</span><b>{m.title}</b><p>{m.snippet||"Public web/news mention."}</p><a href={m.url} target="_blank" rel="noreferrer">{m.source} <ExternalLink size={12}/></a></article>)}</div>:<p>No recent mentions returned by the current public-search layer.</p>}</section>
 </div><aside className="dossierAside"><section className="value"><span className="micro inverse">RECOMMENDED NEXT MOVE</span><strong className="valueAction">{timing(selected.currentStage)}</strong><p>Target: {target?.role}</p></section><section className="panel"><span className="micro">SOURCE PROVENANCE</span><h2>Evidence behind this project.</h2>{selected.sources.map(s=><div className="reason" key={s}><span>✓</span>{s}</div>)}<p>First seen: {dateText(selected.firstSeen)}<br/>Last signal: {dateText(selected.lastSeen)}</p></section><section className="panel"><span className="micro">SALES ACTION CENTER</span><h2>Turn project intelligence into outreach.</h2><div className="actionStack"><button className="primary" onClick={()=>generateAction("email")}><Mail size={15}/> Draft project email</button><button className="secondary" onClick={()=>generateAction("call")}><Phone size={15}/> Prepare call brief</button><button className="secondary" onClick={()=>generateAction("proposal")}><FileText size={15}/> Prepare opportunity brief</button></div>{actionOutput&&<div className="actionOutput"><span className="micro">GENERATED DRAFT — REVIEW BEFORE USE</span><pre>{actionOutput}</pre></div>}</section></aside></div></section>}

 {view==="market"&&<section className="page"><div className="intro"><div><span className="micro">MARKET INTELLIGENCE</span><h1>Measure projects, not duplicated notices.</h1><p>The Project Entity layer converts {rawSignalCount} raw source records into {projects.length} canonical market opportunities for {company}.</p></div></div><div className="metrics"><Metric label="RAW SIGNALS" value={String(rawSignalCount)} note="current ingestion window"/><Metric label="CANONICAL PROJECTS" value={String(projects.length)} note="entity-resolved market"/><Metric label="CORROBORATED" value={String(multiSignalCount)} note=">1 signal per project"/><Metric label="ACTIVE SOURCES" value={String(sources.filter(x=>x.ok).length)} note={fetchedAt?`rebuilt ${new Date(fetchedAt).toLocaleTimeString()}`:"source health"}/></div><section className="darkCallout"><Target size={24}/><span className="micro inverse">NEXT DATA MOAT</span><h2>Project → stakeholder graph → person → relationship history.</h2><p>Canonical projects are now the stable object onto which owner, developer, architect, MEP, contractor, installer, contacts, CRM activity and won/lost feedback can be attached.</p></section></section>}
 {view==="pricing"&&<section className="page"><div className="intro"><div><span className="micro">ROI & PRICING</span><h1>Priced against qualified sales opportunity value.</h1><p>Target pricing remains €499 Professional and €899 Growth, with a €500 validation pilot.</p></div></div><div className="prices"><article><span className="micro">PILOT</span><strong>€500</strong><small>30 days</small><p>One market · one portfolio · canonical project opportunities.</p></article><article><span className="micro">PROFESSIONAL</span><strong>€499</strong><small>/ month</small><p>One country · 3 users · live project dossiers.</p></article><article className="featured"><span className="micro inverse">GROWTH</span><strong>€899</strong><small>/ month</small><p>Benelux · enrichment · workflows · CRM direction.</p></article><article><span className="micro">ENTERPRISE</span><strong>€1.5k+</strong><small>/ month</small><p>Multiple markets · API · custom scoring · relationship intelligence.</p></article></div></section>}
 </main></div>
}
