"use client";

import Link from "next/link";
import {
  ArrowRight, Building2, ChevronRight, CircleDollarSign, Crosshair, ExternalLink,
  FileText, Gauge, LoaderCircle, Mail, Menu, Newspaper, Phone, Radar, RefreshCw,
  Search, SlidersHorizontal, Target, Users, X
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type View="overview"|"opportunities"|"profile"|"dossier"|"market"|"pricing";
type Analysis={company:string;hostname:string;source:"website"|"curated-fallback";categories:{name:string;applications:string;confidence:number}[];idealProjects:string[];analyzedAt:string};
type Opportunity={id:string;title:string;published:string|null;buyer:string;noticeType:string;source:string;country:string;stage:string;relevance:number;customerScore:number;matchedProducts:string[];why:string;href:string;live:boolean};
type SourceStatus={source:string;ok:boolean;count:number;error:string|null};
type Enrichment={ok:boolean;company:string;website:string|null;websiteTitle:string|null;phones:string[];emails:string[];linkedinCompany:string|null;people:{name:string;title:string;linkedin:string;snippet:string}[];mentions:{title:string;url:string;snippet:string;source:string;published?:string}[];confidence:{website:number;contacts:number;people:number;mentions:number}};

const nav=[["overview","Overview",Radar],["opportunities","Opportunities",Crosshair],["profile","Market profile",SlidersHorizontal],["market","Market intelligence",Gauge],["pricing","ROI & pricing",CircleDollarSign]] as const;
const defaultAnalysis:Analysis={company:"Systemair",hostname:"systemair.com",source:"curated-fallback",categories:[{name:"Air handling units",applications:"Hospitals · hotels · offices · schools",confidence:98},{name:"Commercial ventilation",applications:"Broad commercial buildings",confidence:98},{name:"Fire & smoke ventilation",applications:"Hospitals · public buildings · logistics",confidence:94},{name:"Heat recovery",applications:"Energy-efficient new build · renovation",confidence:92}],idealProjects:["Hospitals","Hotels","Offices","Schools","Public buildings","Logistics","Renovation"],analyzedAt:""};

function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="metric"><span className="micro">{label}</span><strong>{value}</strong><small>{note}</small></article>}
function targetFor(stage:string){if(stage==="planning")return{role:"Architect / MEP consultant",reason:"Early planning stage — influence design intent before specification hardens."};if(stage==="permit")return{role:"Owner / developer + engineering team",reason:"Permit stage — project is real enough to qualify while technical choices may still move."};return{role:"Procurement / contractor / integrator",reason:"Procurement stage — specification influence is lower, so pursue buying and delivery stakeholders."}}
function timing(stage:string){if(stage==="planning")return"Engage now — specification window";if(stage==="permit")return"Engage within days";return"Act now — procurement active"}
function dateText(v?:string|null){if(!v)return"Date unavailable";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString()}

export default function ProjectSignalApp(){
 const[view,setView]=useState<View>("overview");const[open,setOpen]=useState(false);const[website,setWebsite]=useState("https://www.systemair.com");const[analysis,setAnalysis]=useState<Analysis>(defaultAnalysis);const[profileLoading,setProfileLoading]=useState(false);const[profileError,setProfileError]=useState("");
 const[items,setItems]=useState<Opportunity[]>([]);const[sources,setSources]=useState<SourceStatus[]>([]);const[feedLoading,setFeedLoading]=useState(true);const[feedError,setFeedError]=useState("");const[fetchedAt,setFetchedAt]=useState("");const[selected,setSelected]=useState<Opportunity|null>(null);const[actionOutput,setActionOutput]=useState("");
 const[enrichment,setEnrichment]=useState<Enrichment|null>(null);const[enriching,setEnriching]=useState(false);const[enrichError,setEnrichError]=useState("");
 const[query,setQuery]=useState("");
 const company=analysis.company||analysis.hostname;const go=(v:View)=>{setView(v);setOpen(false);window.scrollTo({top:0,behavior:"instant"})};

 useEffect(()=>{try{const saved=localStorage.getItem("projectsignal-profile");if(saved){const p=JSON.parse(saved);setAnalysis(p);setWebsite(`https://${p.hostname}`)}}catch{}},[]);
 useEffect(()=>{loadFeed(analysis)},[analysis]);

 async function loadFeed(p:Analysis){setFeedLoading(true);setFeedError("");try{const qs=new URLSearchParams({company:p.company,products:p.categories.map(x=>x.name).join("|"),countries:"NL|BE"});const r=await fetch(`/api/live-projects?${qs.toString()}`,{cache:"no-store"});const d=await r.json();if(!d.ok)throw new Error(d.error||"Live sources unavailable");setItems(d.items||[]);setSources(d.sources||[]);setFetchedAt(d.fetchedAt||"")}catch(e){setFeedError(e instanceof Error?e.message:"Feed unavailable");setItems([])}finally{setFeedLoading(false)}}
 async function analyze(){setProfileLoading(true);setProfileError("");try{const r=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({website})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Analysis failed");setAnalysis(d);localStorage.setItem("projectsignal-profile",JSON.stringify(d));go("opportunities")}catch(e){setProfileError(e instanceof Error?e.message:"Analysis failed")}finally{setProfileLoading(false)}}
 async function enrich(item:Opportunity){setEnriching(true);setEnrichError("");setEnrichment(null);try{const qs=new URLSearchParams({company:item.buyer,country:item.country});const r=await fetch(`/api/enrich-account?${qs.toString()}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Enrichment failed");setEnrichment(d)}catch(e){setEnrichError(e instanceof Error?e.message:"Enrichment failed")}finally{setEnriching(false)}}
 function openDossier(item:Opportunity){setSelected(item);setActionOutput("");setEnrichment(null);setEnrichError("");go("dossier");enrich(item)}

 const high=useMemo(()=>items.filter(x=>x.customerScore>=80).length,[items]);const early=useMemo(()=>items.filter(x=>x.stage==="planning"||x.stage==="permit").length,[items]);const top=items[0]||null;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return items;return items.filter(x=>`${x.title} ${x.buyer} ${x.source} ${x.stage} ${(x.matchedProducts||[]).join(" ")}`.toLowerCase().includes(q))},[items,query]);
 function contactReadiness(item:Opportunity){let s=34;if(item.buyer&&!/public buyer|authority/i.test(item.buyer))s+=18;if(item.href)s+=10;if(item.matchedProducts?.length)s+=15;if(item.stage==="planning"||item.stage==="permit")s+=8;if(item.published)s+=5;if(enrichment?.emails?.length||enrichment?.phones?.length)s+=10;if(enrichment?.people?.length)s+=8;return Math.min(98,s)}
 function generateAction(kind:"email"|"call"|"proposal"){if(!selected)return;const products=selected.matchedProducts?.length?selected.matchedProducts.join(", "):analysis.categories.slice(0,2).map(x=>x.name).join(", ");const target=targetFor(selected.stage);const person=enrichment?.people?.[0];const salutation=person?.name?person.name:"[Name]";if(kind==="email")setActionOutput(`Subject: ${selected.title} — ${products}\n\nHi ${salutation},\n\nI noticed ${selected.title} and that ${selected.buyer} is connected to the current ${selected.stage} stage. We work with ${products} at ${company}.\n\nGiven the project timing, it may be useful to compare the technical requirements before the next decision point. Would a short 15-minute call next week be useful?\n\nBest regards,\n[Sales rep]\n${company}`);if(kind==="call")setActionOutput(`CALL BRIEF\n\nProject: ${selected.title}\nTarget account: ${selected.buyer}\nTarget role: ${target.role}\nSuggested contact: ${person?.name||"identify named decision maker"}\nWhy now: ${target.reason}\nRelevant products: ${products}\n\nOPENING\n“We are tracking ${selected.title} and noticed the project is at ${selected.stage} stage. I wanted to understand who is leading the building-services specification.”\n\nQUESTIONS\n1. Who owns the HVAC/building-services specification?\n2. Which product families are already specified?\n3. When is the next design/procurement milestone?\n4. Are alternative suppliers still being evaluated?\n5. Who should receive technical documentation?`);if(kind==="proposal")setActionOutput(`PROJECT-SPECIFIC ONE-PAGER\n\nOpportunity: ${selected.title}\nCustomer: ${company}\nTarget account: ${selected.buyer}\nStage: ${selected.stage}\nOpportunity score: ${selected.customerScore}/100\nRelevant portfolio: ${products}\n\nVALUE PROPOSITION\nPosition ${company} around the matched product families and the current project stage. Validate requirements with the specification owner before preparing a final technical/commercial quote.\n\nNEXT STEP\nConfirm specification owner → validate requirements → send technical pack → schedule project review.`)}
 const target=selected?targetFor(selected.stage):null;

 return <div className="shell"><aside className={`sidebar ${open?"open":""}`}><div className="brandRow"><button className="brand" onClick={()=>go("overview")}><span className="brandMark"><Radar size={20}/></span>PROJECTSIGNAL</button><button className="icon mobile" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="workspace"><span className="micro inverse">WORKSPACE</span><b>Benelux / Building systems</b><span>{company} live profile</span></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><Icon size={17}/>{label}</button>)}</nav><div className="sideFoot"><span className="dot"/><div><b>Live validation MVP</b><span>Public signals → account dossier → sales action</span></div></div></aside>
 <main><header className="topbar"><button className="icon mobile" onClick={()=>setOpen(true)}><Menu size={19}/></button><span className="micro">PROJECTSIGNAL / {view.toUpperCase()}</span><div className="topActions"><Link className="textBtn" href="/live">Raw live feed <ExternalLink size={14}/></Link><button className="textBtn" onClick={()=>go("profile")}>Edit profile <ArrowRight size={15}/></button></div></header>

 {view==="overview"&&<section className="page"><div className="hero"><div><span className="kicker"><span className="dot orange"/> SALES-READY CONSTRUCTION INTELLIGENCE</span><h1>Find the project. Find the buyer. <em>Know what to say.</em></h1><p>ProjectSignal turns live planning, permit and procurement signals into company-specific sales opportunities, enriches the target account and prepares the route from signal to conversation.</p><div className="actions"><button className="primary" onClick={()=>go("opportunities")}>Open live opportunities <ArrowRight size={16}/></button><button className="secondary" onClick={()=>go("profile")}>Analyse another company</button></div></div><div className="railCard"><div className="railHead"><span className="micro inverse">TOP LIVE SIGNAL FOR {company.toUpperCase()}</span><span>{top?`${top.customerScore} / 100`:"—"}</span></div><div className="railProject"><b>{top?.title||"Loading live opportunities…"}</b><small>{top?`${top.country} · ${top.source}`:"NL + BE public sources"}</small></div><div className="rail">{["Planning","Permit","Specification","Procurement","Delivery"].map((s,i)=>{const idx=top?.stage==="planning"?0:top?.stage==="permit"?1:3;return <div className={`${idx===i?"current":""} ${idx>i?"done":""}`} key={s}><span/><b>{s}</b>{idx===i&&<small>Current signal stage</small>}</div>})}</div>{top&&<button className="railAction railActionButton" onClick={()=>openDossier(top)}><span className="micro inverse">NEXT COMMERCIAL MOVE</span><b>{timing(top.stage)}</b><small>Open sales dossier →</small></button>}</div></div><div className="thesis"><article><span className="micro">DISCOVER</span><b>Live project signals.</b><p>Planning, permits and procurement from public sources.</p></article><article className="accent"><span className="micro">ENRICH</span><b>Account + people + mentions.</b><p>Website, public contacts, LinkedIn profiles and recent signals.</p></article><article><span className="micro">ACT</span><b>Turn signal into conversation.</b><p>Email, call brief, one-pager and next-step workflow.</p></article></div></section>}

 {view==="profile"&&<section className="page"><div className="intro"><div><span className="micro">MARKET PROFILE</span><h1>Teach ProjectSignal what your company can sell.</h1><p>The active product profile is used directly in the live opportunity ranking.</p></div></div><div className="profileGrid"><div className="form"><label>COMPANY WEBSITE<input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://www.company.com"/></label><div><span className="micro">QUICK DEMOS</span><div className="actions"><button className="secondary" onClick={()=>setWebsite("https://www.systemair.com")}>Systemair</button><button className="secondary" onClick={()=>setWebsite("https://www.renson.net")}>Renson</button><button className="secondary" onClick={()=>setWebsite("https://www.zehnder.nl")}>Zehnder</button><button className="secondary" onClick={()=>setWebsite("https://www.daikin.be")}>Daikin</button></div></div>{profileError&&<p className="urgent">{profileError}</p>}<button className="primary" onClick={analyze} disabled={profileLoading}>{profileLoading?<><LoaderCircle size={16} className="spin"/> Analysing…</>:<>Analyse portfolio & rank live market <ArrowRight size={16}/></>}</button></div><aside className="derived"><span className="micro">ACTIVE PROFILE · {analysis.source==="website"?"WEBSITE-DETECTED":"CURATED FALLBACK"}</span><h2>{company}</h2>{analysis.categories.map(x=><div key={x.name}><b>{x.name}</b><span>{x.applications} · confidence {x.confidence}%</span></div>)}</aside></div></section>}

 {view==="opportunities"&&<section className="page"><div className="intro"><div><span className="micro">LIVE PIPELINE FOR {company.toUpperCase()}</span><h1>Where should sales spend time today?</h1><p>The main pipeline now uses the same live NL/BE sources as `/live`; the old five-project demo list is no longer the primary dataset.</p></div><button className="secondary" onClick={()=>loadFeed(analysis)} disabled={feedLoading}><RefreshCw size={15}/>{feedLoading?"Refreshing…":"Refresh"}</button></div><div className="metrics"><Metric label="LIVE OPPORTUNITIES" value={feedLoading?"—":String(items.length)} note="deduplicated current signals"/><Metric label="HIGH FIT" value={feedLoading?"—":String(high)} note="customer score ≥ 80"/><Metric label="EARLY STAGE" value={feedLoading?"—":String(early)} note="planning + permit"/><Metric label="ACTIVE SOURCES" value={String(sources.filter(x=>x.ok).length)} note={fetchedAt?`refreshed ${new Date(fetchedAt).toLocaleTimeString()}`:"source health"}/></div>{feedError&&<div className="liveError"><b>Live feed unavailable</b><span>{feedError}</span></div>}<div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project, account, source, stage…"/></div><span className="micro">CLICK ANY ROW → SALES DOSSIER</span></div><div className="tableWrap"><table><thead><tr><th>Fit</th><th>Opportunity</th><th>Matched products</th><th>Stage</th><th>Known account</th><th>Action</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="clickable" onClick={()=>openDossier(x)}><td><span className="score">{x.customerScore}</span></td><td><b>{x.title}</b><span>{x.country} · {x.source} · {dateText(x.published)}</span></td><td>{x.matchedProducts?.length?x.matchedProducts.slice(0,2).join(" · "):"Portfolio fit not explicit"}</td><td><span className={`stage stage-${x.stage}`}>{x.stage}</span></td><td>{x.buyer}</td><td className="urgent actionCell">Open dossier <ChevronRight size={14}/></td></tr>)}</tbody></table>{!feedLoading&&filtered.length===0&&<div className="emptyState">No opportunities match the current filter.</div>}</div></section>}

 {view==="dossier"&&selected&&<section className="page dossierPage"><button className="back" onClick={()=>go("opportunities")}>← Back to live opportunities</button><div className="projectHead"><div><span className="micro">SALES DOSSIER / {selected.source.toUpperCase()}</span><h1>{selected.title}</h1><p>{selected.country} · {selected.noticeType} · published {dateText(selected.published)}</p></div><div className="bigScore"><span>OPPORTUNITY SCORE</span><strong>{selected.customerScore}</strong><small>/100</small></div></div><div className="dossierSummary"><Metric label="STAGE" value={selected.stage.toUpperCase()} note={timing(selected.stage)}/><Metric label="CONTACT READINESS" value={`${contactReadiness(selected)}%`} note="public-data completeness"/><Metric label="MATCHED PRODUCTS" value={String(selected.matchedProducts?.length||0)} note={selected.matchedProducts?.slice(0,2).join(" · ")||"not explicit"}/><Metric label="DATA SOURCE" value="LIVE" note={selected.source}/></div>
 <div className="dossierGrid"><div className="dossierMain">
 <section className="panel"><div className="panelHead"><div><span className="micro">WHY THIS MATTERS</span><h2>Commercial interpretation for {company}</h2></div><span className="high">{selected.customerScore>=80?"HIGH FIT":"QUALIFIED"}</span></div><p>{selected.why}</p><div className="reason"><span>✓</span>{timing(selected.stage)}</div>{selected.matchedProducts?.map(p=><div className="reason" key={p}><span>✓</span>{p} matched to the active {company} profile</div>)}<div className="sourceProof"><span className="micro">SOURCE PROVENANCE</span><a href={selected.href} target="_blank" rel="noreferrer">Open original {selected.source} record <ExternalLink size={13}/></a></div></section>
 <section className="panel"><div className="panelHead"><div><span className="micro">STAKEHOLDER ROUTE</span><h2>Who should sales target now?</h2></div></div><div className="stakeFlow"><article className="stakeKnown"><span>KNOWN ACCOUNT</span><b>{selected.buyer}</b><small>Identified from the public project signal</small></article><ArrowRight size={18}/><article><span>PRIORITY ROLE</span><b>{target?.role}</b><small>{target?.reason}</small></article><ArrowRight size={18}/><article className={enrichment?.people?.length?"stakeKnown":"stakePending"}><span>NAMED CONTACT</span><b>{enrichment?.people?.[0]?.name||"Research in progress"}</b><small>{enrichment?.people?.[0]?.title||"LinkedIn/public web enrichment"}</small></article></div></section>
 <section className="panel"><div className="panelHead"><div><span className="micro">ACCOUNT DOSSIER</span><h2>{selected.buyer}</h2></div><Building2 size={20}/></div>{enriching?<div className="liveLoading"><LoaderCircle size={18} className="spin"/> Researching public web sources…</div>:enrichError?<div className="liveError"><b>Enrichment unavailable</b><span>{enrichError}</span></div>:enrichment&&<><div className="accountFacts"><div><span>Website</span><b>{enrichment.website?<a href={enrichment.website} target="_blank" rel="noreferrer">{enrichment.website.replace(/^https?:\/\//,'')} <ExternalLink size={12}/></a>:"Not found"}</b></div><div><span>Phone</span><b>{enrichment.phones[0]||"Not found"}</b></div><div><span>Email</span><b>{enrichment.emails[0]||"Not found"}</b></div><div><span>LinkedIn</span><b>{enrichment.linkedinCompany?<a href={enrichment.linkedinCompany} target="_blank" rel="noreferrer">Company profile <ExternalLink size={12}/></a>:"Not found"}</b></div></div><div className="confidenceLine"><span>Website {enrichment.confidence.website}%</span><span>Contacts {enrichment.confidence.contacts}%</span><span>People {enrichment.confidence.people}%</span><span>Mentions {enrichment.confidence.mentions}%</span></div></>}</section>
 <section className="panel"><div className="panelHead"><div><span className="micro">RELEVANT PEOPLE</span><h2>Public professional profiles</h2></div><Users size={20}/></div>{enriching?<p>Searching roles…</p>:enrichment?.people?.length?<div className="peopleList">{enrichment.people.map(p=><article key={p.linkedin}><div><b>{p.name}</b><span>{p.title}</span><small>{p.snippet}</small></div><a href={p.linkedin} target="_blank" rel="noreferrer">LinkedIn <ExternalLink size={12}/></a></article>)}</div>:<p>No named public profiles found automatically. Use the manual research link below rather than inventing a contact.</p>}<div className="actions"><a className="secondary" target="_blank" rel="noreferrer" href={`https://www.google.com/search?q=${encodeURIComponent("site:linkedin.com/in "+selected.buyer+" engineering director procurement")}`}>Manual people search <ExternalLink size={14}/></a></div></section>
 <section className="panel"><div className="panelHead"><div><span className="micro">RECENT INTELLIGENCE</span><h2>What has been mentioned publicly?</h2></div><Newspaper size={20}/></div>{enriching?<p>Collecting mentions…</p>:enrichment?.mentions?.length?<div className="mentionList">{enrichment.mentions.slice(0,8).map((m,i)=><article key={`${m.url}-${i}`}><span>{m.published?dateText(m.published):m.source}</span><b>{m.title}</b><p>{m.snippet||"Public web/news mention."}</p><a href={m.url} target="_blank" rel="noreferrer">{m.source} <ExternalLink size={12}/></a></article>)}</div>:<p>No recent mentions were returned by the public search layer.</p>}</section>
 </div><aside className="dossierAside"><section className="value"><span className="micro inverse">RECOMMENDED NEXT MOVE</span><strong className="valueAction">{timing(selected.stage)}</strong><p>Target: {target?.role}</p></section><section className="panel"><span className="micro">SALES ACTION CENTER</span><h2>Turn intelligence into outreach.</h2><div className="actionStack"><button className="primary" onClick={()=>generateAction("email")}><Mail size={15}/> Draft project email</button><button className="secondary" onClick={()=>generateAction("call")}><Phone size={15}/> Prepare call brief</button><button className="secondary" onClick={()=>generateAction("proposal")}><FileText size={15}/> Prepare one-pager</button></div>{actionOutput&&<div className="actionOutput"><span className="micro">GENERATED DRAFT — REVIEW BEFORE USE</span><pre>{actionOutput}</pre></div>}</section><section className="panel"><span className="micro">SALES WORKFLOW</span><h2>What happens next.</h2><div className="nextSteps"><div><b>1</b><span>Verify target account</span></div><div><b>2</b><span>Select decision maker</span></div><div><b>3</b><span>Send personalised outreach</span></div><div><b>4</b><span>Create CRM opportunity</span></div><div><b>5</b><span>Monitor project changes</span></div><div><b>6</b><span>Capture won/lost feedback</span></div></div></section></aside></div></section>}

 {view==="market"&&<section className="page"><div className="intro"><div><span className="micro">MARKET INTELLIGENCE</span><h1>See the market your CRM does not.</h1><p>Live coverage for {company}, plus sales readiness and enrichment.</p></div></div><div className="metrics"><Metric label="LIVE SIGNALS" value={String(items.length)} note="current source window"/><Metric label="HIGH FIT" value={String(high)} note="score ≥ 80"/><Metric label="EARLY STAGE" value={String(early)} note="planning + permit"/><Metric label="PRODUCT CATEGORIES" value={String(analysis.categories.length)} note="active profile"/></div><section className="darkCallout"><Target size={24}/><span className="micro inverse">PRODUCT DIRECTION</span><h2>Discover → qualify → enrich → contact → follow up → learn.</h2><p>The live feed is now the start of the workflow, not the end. The product is becoming a sales execution layer on top of construction intelligence.</p></section></section>}
 {view==="pricing"&&<section className="page"><div className="intro"><div><span className="micro">ROI & PRICING</span><h1>Priced against sales intelligence value, not record volume.</h1><p>Target pricing remains €499 Professional and €899 Growth, with a €500 validation pilot.</p></div></div><div className="prices"><article><span className="micro">PILOT</span><strong>€500</strong><small>30 days</small><p>One market · one portfolio · qualified opportunities.</p></article><article><span className="micro">PROFESSIONAL</span><strong>€499</strong><small>/ month</small><p>One country · 3 users · live dossiers.</p></article><article className="featured"><span className="micro inverse">GROWTH</span><strong>€899</strong><small>/ month</small><p>Benelux · enrichment · workflows · CRM direction.</p></article><article><span className="micro">ENTERPRISE</span><strong>€1.5k+</strong><small>/ month</small><p>Multiple markets · API · custom scoring · relationship intelligence.</p></article></div></section>}
 </main></div>
}
