"use client";

import { ArrowRight, CircleDollarSign, Crosshair, Gauge, Menu, Radar, Search, SlidersHorizontal, Sparkles, Target, Users, X } from "lucide-react";
import { useState } from "react";

type View = "overview" | "opportunities" | "profile" | "project" | "market" | "pricing";

const nav = [
  ["overview", "Overview", Radar],
  ["opportunities", "Opportunities", Crosshair],
  ["profile", "Market profile", SlidersHorizontal],
  ["market", "Market intelligence", Gauge],
  ["pricing", "ROI & pricing", CircleDollarSign],
] as const;

const rows = [
  [98,"Erasmus MC — New Campus","Rotterdam, NL","Hospital & research","Design","€1.8–3.3M","Engage now"],
  [96,"ETZ Elisabeth — Phase 2","Tilburg, NL","Hospital","Design","€1.1–2.0M","Engage now"],
  [91,"Airport Business District","Brussels, BE","Hotel + office + transport","Design","€450–900k","Engage now"],
  [88,"Lumière","Rotterdam, NL","Mixed-use","Development","€300–650k","1–3 months"],
  [86,"Bravis Hospital","West-Brabant, NL","All-electric hospital","Contractor selected","€700k–1.4M","Target integrator"],
] as const;

function Metric({label,value,note}:{label:string;value:string;note:string}) {
  return <article className="metric"><span className="micro">{label}</span><strong>{value}</strong><small>{note}</small></article>;
}

export default function Home(){
  const [view,setView]=useState<View>("overview");
  const [open,setOpen]=useState(false);
  const go=(v:View)=>{setView(v);setOpen(false);window.scrollTo({top:0,behavior:"instant"})};
  return <div className="shell">
    <aside className={`sidebar ${open?"open":""}`}>
      <div className="brandRow"><button className="brand" onClick={()=>go("overview")}><span className="brandMark"><Radar size={20}/></span>PROJECTSIGNAL</button><button className="icon mobile" onClick={()=>setOpen(false)}><X size={18}/></button></div>
      <div className="workspace"><span className="micro inverse">WORKSPACE</span><b>Benelux / HVAC</b><span>Systemair demo profile</span></div>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><Icon size={17}/>{label}</button>)}</nav>
      <div className="sideFoot"><span className="dot"/><div><b>Validation demo</b><span>Modelled data + real project examples</span></div></div>
    </aside>
    <main>
      <header className="topbar"><button className="icon mobile" onClick={()=>setOpen(true)}><Menu size={19}/></button><span className="micro">PROJECTSIGNAL / {view.toUpperCase()}</span><button className="textBtn" onClick={()=>go("profile")}>Edit profile <ArrowRight size={15}/></button></header>

      {view==="overview"&&<section className="page">
        <div className="hero">
          <div><span className="kicker"><span className="dot orange"/> PRODUCT OPPORTUNITY INTELLIGENCE</span><h1>Know which projects need your products <em>before procurement starts.</em></h1><p>ProjectSignal converts fragmented construction activity into a ranked sales pipeline: product fit, potential value, influence window and the stakeholder your team should approach next.</p><div className="actions"><button className="primary" onClick={()=>go("profile")}>Build market profile <ArrowRight size={16}/></button><button className="secondary" onClick={()=>go("opportunities")}>See demo pipeline</button></div></div>
          <div className="railCard"><div className="railHead"><span className="micro inverse">LIVE OPPORTUNITY SIGNAL</span><span>98 / 100</span></div><div className="railProject"><b>Erasmus MC — New Campus</b><small>Rotterdam · Hospital & research · &gt;100,000 m²</small></div><div className="rail">{["Concept","Design","Specification","Tender","Installation"].map((s,i)=><div className={`${i===1?"current":""} ${i<1?"done":""}`} key={s}><span/><b>{s}</b>{i===1&&<small>Influence window open</small>}</div>)}</div><div className="railAction"><span className="micro inverse">NEXT COMMERCIAL MOVE</span><b>Engage engineering/specification team now</b><small>Potential portfolio value: €1.8–3.3M*</small></div></div>
        </div>
        <div className="thesis"><article><span className="micro">TRADITIONAL DATABASE</span><b>Shows what is being built.</b><p>Projects, filters and contacts. Sales still has to research relevance.</p></article><article className="accent"><span className="micro">PROJECTSIGNAL</span><b>Shows what your team should pursue.</b><p>Customer × Product × Project × Timing → one qualified signal.</p></article><article><span className="micro">ACTION LAYER</span><b>Who to influence, and when.</b><p>Stage-aware route to architect, engineer, MEP, contractor or integrator.</p></article></div>
        <div className="sectionTitle"><span className="micro">THE PRODUCT THESIS</span><h2>Less project noise. More accountable sales decisions.</h2></div>
      </section>}

      {view==="opportunities"&&<section className="page"><div className="intro"><div><span className="micro">YOUR BENELUX PIPELINE</span><h1>Opportunities worth a sales conversation.</h1><p>Ranked specifically for the selected HVAC portfolio. Not a generic project feed.</p></div><button className="primary" onClick={()=>go("profile")}>Refine profile</button></div><div className="metrics"><Metric label="RELEVANT ACTIVE PROJECTS" value="187" note="Belgium + Netherlands"/><Metric label="MODELLED PRODUCT VALUE" value="€46.8M" note="addressable opportunity"/><Metric label="HIGH PRIORITY" value="31" note="score ≥ 85"/><Metric label="ACTION NOW" value="14" note="influence window open"/></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search projects, cities, companies…"/></div><button className="secondary"><SlidersHorizontal size={15}/> Filters</button></div><div className="tableWrap"><table><thead><tr><th>Score</th><th>Project</th><th>Stage</th><th>Your potential</th><th>Timing</th><th/></tr></thead><tbody>{rows.map((r,i)=><tr key={r[1]} className={i===0?"clickable":""} onClick={()=>i===0&&go("project")}><td><span className="score">{r[0]}</span></td><td><b>{r[1]}</b><span>{r[2]} · {r[3]}</span></td><td><span className="stage">{r[4]}</span></td><td className="money">{r[5]}</td><td className={String(r[6]).includes("Engage")?"urgent":""}>{r[6]}</td><td><ArrowRight size={16}/></td></tr>)}</tbody></table></div><div className="ask"><div><Sparkles size={17}/><span className="micro inverse">ASK PROJECTSIGNAL</span></div><input defaultValue="Show hospital projects where AHU specification may still be open"/><button>Ask</button></div></section>}

      {view==="profile"&&<section className="page"><div className="intro"><div><span className="micro">MARKET PROFILE</span><h1>Teach ProjectSignal what “relevant” means to you.</h1><p>The live product will derive a commercial project profile from the company website and catalogue instead of forcing sales teams through a maze of generic filters.</p></div></div><div className="profileGrid"><form className="form" onSubmit={e=>{e.preventDefault();go("opportunities")}}><label>COMPANY WEBSITE<input defaultValue="https://www.systemair.com"/></label><label>MARKETS<select defaultValue="Benelux"><option>Benelux</option><option>Belgium</option><option>Netherlands</option><option>Benelux + France</option></select></label><label>PRODUCT PORTFOLIO<textarea defaultValue={"Air handling units\nCommercial ventilation\nFans\nFire & smoke ventilation\nHeat recovery systems"}/></label><label>IDEAL PROJECTS<textarea defaultValue={"Hospitals\nHotels > 80 rooms\nOffices > 5,000 m²\nLogistics > 10,000 m²\nIndustrial buildings\nSchools"}/></label><button className="primary">Analyse portfolio & find signals <ArrowRight size={16}/></button></form><aside className="derived"><span className="micro">DEMO OUTPUT</span><h2>What the system derives.</h2>{[["Commercial AHU","Hospitals · hotels · schools · offices"],["Ventilation","Broad commercial applicability"],["Fire & smoke","Complex/public buildings"],["Heat recovery","Energy-intensive renovation & new build"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}<section><b>No keyword maze.</b><p>Website and product catalogue become the starting point for scoring.</p></section></aside></div></section>}

      {view==="project"&&<section className="page"><button className="back" onClick={()=>go("opportunities")}>← Back to opportunities</button><div className="projectHead"><div><span className="micro">QUALIFIED OPPORTUNITY / ROTTERDAM</span><h1>Erasmus MC — New Campus</h1><p>Hospital & research · &gt;100,000 m² · Design stage</p></div><div className="bigScore"><span>OPPORTUNITY SCORE</span><strong>98</strong><small>/100</small></div></div><div className="projectGrid"><div><section className="panel"><div className="panelHead"><h2>Why this project matches your portfolio</h2><span className="high">HIGH SIGNAL</span></div>{["Large hospital + research environment","Strong AHU / chiller / heat-pump applicability","Technical design is still progressing","Engineering consultants are identified","Specification influence window appears open"].map(x=><div className="reason" key={x}><span>✓</span>{x}</div>)}</section><section className="panel"><div className="panelHead"><h2>What you could sell here</h2><span className="micro">MODELLED — NOT PROCUREMENT DATA</span></div><table><thead><tr><th>Product family</th><th>Fit</th><th>Modelled potential</th></tr></thead><tbody><tr><td>Air handling units</td><td>97%</td><td>€600k–1.1M</td></tr><tr><td>Chillers</td><td>91%</td><td>€500–900k</td></tr><tr><td>Commercial heat pumps</td><td>89%</td><td>€400–800k</td></tr><tr><td>Controls / BMS integration</td><td>76%</td><td>€300–500k</td></tr></tbody></table></section></div><aside><section className="value"><span className="micro inverse">YOUR MODELLED OPPORTUNITY</span><strong>€1.8–3.3M</strong><p>Portfolio-addressable equipment value based on project type, scale and stage.</p></section><section className="panel"><h2>Signal rail</h2><div className="compactRail">{["Concept","Design","Specification","Tender","Install"].map((s,i)=><div className={`${i===1?"current":""} ${i<1?"done":""}`} key={s}><span/><b>{s}</b>{i===1&&<small>YOU ARE HERE</small>}</div>)}</div><div className="actionBox"><span className="micro">RECOMMENDED ACTION</span><b>Engage now</b><p>Prioritise engineering/specification stakeholders before requirements freeze.</p></div></section><section className="panel"><h2>Who to approach</h2><div className="stake"><span>Owner</span><b>Erasmus MC</b></div><div className="stake"><span>Engineering adviser</span><b>Arcadis</b></div><div className="stake"><span>Technical consultants</span><b>Deerns · Haskoning · Peutz</b></div></section></aside></div></section>}

      {view==="market"&&<section className="page"><div className="intro"><div><span className="micro">MARKET INTELLIGENCE</span><h1>See the market your CRM does not.</h1><p>Coverage and timing across the selected product portfolio.</p></div></div><div className="metrics"><Metric label="MATCHED PROJECTS" value="843" note="selected markets"/><Metric label="ADDRESSABLE MARKET" value="€1.27B" note="modelled portfolio value"/><Metric label="0–6 MONTH PIPELINE" value="€331M" note="timing-adjusted"/><Metric label="NOT IN CRM" value="71%" note="coverage gap"/></div><section className="darkCallout"><Target size={24}/><span className="micro inverse">THE COMMERCIAL QUESTION</span><h2>Which 20 opportunities deserve our sales capacity this quarter?</h2><p>ProjectSignal is designed to answer that question, rather than maximize the number of project records shown.</p></section></section>}

      {view==="pricing"&&<section className="page"><div className="intro"><div><span className="micro">ROI & PRICING</span><h1>Priced against intelligence budgets, justified by one incremental win.</h1><p>The validation target is project/specification sales where one commercial opportunity can be worth six figures.</p></div></div><div className="prices"><article><span className="micro">PILOT</span><strong>€500</strong><small>30 days</small><p>One market · one product portfolio · weekly qualified opportunities.</p></article><article><span className="micro">PROFESSIONAL</span><strong>€499</strong><small>/ month</small><p>One country · one product line · 3 users.</p></article><article className="featured"><span className="micro inverse">GROWTH</span><strong>€899</strong><small>/ month</small><p>Benelux · multiple product lines · CRM sync · market analytics.</p></article><article><span className="micro">ENTERPRISE</span><strong>€1.5k+</strong><small>/ month</small><p>Multiple countries · API · custom scoring and enrichment.</p></article></div><section className="roi"><div><span className="micro">SIMPLE ROI EXAMPLE</span><h2>One €150k equipment win at 25% gross margin = €37.5k margin.</h2><p>A €10,788 annual Growth subscription would need substantially less than one additional average win to cover its cost on gross-margin contribution.</p></div><div><strong>~3.5×</strong><span>gross-margin return from one incremental €150k deal</span></div></section></section>}
    </main>
  </div>
}
